// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qotjmigcwgrbnvvfjqpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdGptaWdjd2dyYm52dmZqcXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDQ4MTMsImV4cCI6MjA2MzU4MDgxM30.-ALGYMhgCaB-_OzCkCXZoV0DDtQtKoJJ8HqC2Gp-CTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);